name: master

on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: master
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Env vars
        run: printenv
      - name: Build the Docker image
        run: make docker-build-and-push DOCKERFILE=Dockerfile.production DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }}
