name: master

on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: master
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build the Docker image AMD64
        run: make docker_build ARCH=linux/arm/v6 DOCKERFILE=Dockerfile
      - name: Build the Docker image ARM
        run: make docker_build ARCH=linux/amd64 DOCKERFILE=Dockerfile.amd64
      - name: Push the Docker image
        run: make docker_push DOCKER_USER=beaujr DOCKER_PASS=${{ secrets.DOCKER_PASS }} GITHUB_HEAD_REF=master
